//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.17 at 06:52:23 ÏÂÎç CST 
//


package com.cattsoft.oss.rms.ws.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOCAL_NET_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AREA_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QUERY_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localnetid",
    "areaid",
    "addrname",
    "queryflag"
})
@XmlRootElement(name = "CPN_ADDR_QUERY_NM_REQ")
public class CPNADDRQUERYNMREQ {

    @XmlElement(name = "LOCAL_NET_ID", required = true)
    protected String localnetid;
    @XmlElement(name = "AREA_ID", required = true)
    protected String areaid;
    @XmlElement(name = "ADDR_NAME", required = true)
    protected String addrname;
    @XmlElement(name = "QUERY_FLAG", required = true)
    protected String queryflag;

    /**
     * Gets the value of the localnetid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOCALNETID() {
        return localnetid;
    }

    /**
     * Sets the value of the localnetid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOCALNETID(String value) {
        this.localnetid = value;
    }

    /**
     * Gets the value of the areaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAREAID() {
        return areaid;
    }

    /**
     * Sets the value of the areaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAREAID(String value) {
        this.areaid = value;
    }

    /**
     * Gets the value of the addrname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRNAME() {
        return addrname;
    }

    /**
     * Sets the value of the addrname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRNAME(String value) {
        this.addrname = value;
    }

    /**
     * Gets the value of the queryflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUERYFLAG() {
        return queryflag;
    }

    /**
     * Sets the value of the queryflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUERYFLAG(String value) {
        this.queryflag = value;
    }

}
